title: Automation everywhere
author: Greg Brownstein
email: greg@jagtechnical.com
description: > # this means to ignore newlines until "baseurl:"
  Random automation and powershell musings

# social links
twitter_username: gd_barron # DO NOT include the @ character, or else the build will fail!
github_username:  gdbarron # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
